-- Bunny Training — mystery box encouragement pool.
-- Run after schema.sql. Safe to re-run; duplicates are ignored.
-- Add your own lines here any time and run just the new ones.

insert into phrases (body) values
  ('You showed up today, Bunny. That is the whole secret.'),
  ('Strongest bunny in the whole garden.'),
  ('Every rep today was a promise you kept to yourself.'),
  ('Look at you go. Seriously, look at you.'),
  ('Sweaty, tired, unstoppable.'),
  ('That workout did not stand a chance.'),
  ('Proud of you does not quite cover it.'),
  ('Small hops, big distance. Keep going, Bunny.'),
  ('You are building something that nobody can take from you.'),
  ('Future you just sent a thank you note.'),
  ('Done is done. Go be smug about it.'),
  ('Bunny: 1. Excuses: 0.'),
  ('You did the hard thing before the easy thing. That is discipline.'),
  ('Some days it flows, some days it fights. You won either way.'),
  ('Officially a certified powerhouse.'),
  ('The couch misses you. Too bad.'),
  ('You are so much stronger than the month before this one.'),
  ('That was not luck. That was you.'),
  ('Tiny bunny, enormous willpower.'),
  ('Rest now. You earned every second of it.'),
  ('Consistency looks good on you.'),
  ('You turned a plan into sweat. That is the rare part.'),
  ('Nobody trains this hard by accident.'),
  ('Your body is listening, and it is impressed.'),
  ('Another one in the books, champion.'),
  ('You were tired and you did it anyway. That is the flex.'),
  ('Strong bunny energy detected.'),
  ('This is what taking care of yourself looks like.'),
  ('You are the kind of person who finishes things.'),
  ('Hop by hop, you are getting unrecognizable.'),
  ('Whatever today threw at you, you threw back harder.'),
  ('The mirror is going to start telling stories soon.'),
  ('Warning: confidence levels rising.'),
  ('You just made tomorrow easier.'),
  ('That is a workout you can be genuinely proud of.'),
  ('Soft heart, strong legs.'),
  ('You are allowed to feel amazing right now.'),
  ('Look how far the little bunny has hopped.'),
  ('Excellence is boring and repetitive and you just did it again.'),
  ('You are not behind. You are exactly on your own path.'),
  ('Good things happen to bunnies who finish their sets.'),
  ('You are quietly becoming very hard to beat.'),
  ('Today counted. They all count.'),
  ('Sore tomorrow, unstoppable forever.'),
  ('Your discipline is honestly kind of attractive.'),
  ('Take a breath. You just did something great.'),
  ('The strongest version of you is being built one day like this at a time.'),
  ('You kept going when it got boring. That is the real strength.'),
  ('Certified hopping machine.'),
  ('You are worth every minute you spend on yourself.'),
  ('Done. Now go eat something delicious, you earned it.'),
  ('This is your reminder that you are capable of hard things.'),
  ('Twenty minutes of courage beats zero minutes of perfect.'),
  ('You are the main character of this gym.'),
  ('Momentum is yours now. Do not give it back.'),
  ('Nobody else did this for you today. You did.'),
  ('Strong is a mood and you are wearing it.'),
  ('You are so loved, and so strong, in that order.'),
  ('The carrot is confidence and you just earned a whole basket.'),
  ('See you tomorrow, Bunny. Same fire.')
on conflict (body) do nothing;
